server:
  port: 6056

spring:
  application:
    name: shipment-service
  datasource:
    url: jdbc:h2:mem:devdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

config:
  kafka:
    url: localhost:29092