server:
  port: 6050
  servlet:
    context-path: /orders-service

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:devdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console.enabled: true

config:
  kafka:
    url: localhost:29092

listener:
  id: orders
  topics:
    shipment:
      request: shipment-request
      response: shipment-response
